#!/bin/sh

# Install packer plugin manager for neovim
packer_dir="$XDG_DATA_HOME"/nvim/site/pack/packer/start/packer.nvim
packer_repo_url='https://github.com/wbthomason/packer.nvim'
[ -d "$dir" ] || git clone "$packer_repo_url" "$packer_dir"
