set nocompatible              " be iMproved, required
set runtimepath+=~/.config/vim,~/.config/vim/after
syntax enable
filetype plugin indent on

nnoremap ; :
set relativenumber
set number

set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" clear registers
function! ClearRegs()
    let regs=split('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-"', '\zs')
    for r in regs
        call setreg(r, [])
    endfor
    echo 'Registers cleared.'
endfunction
nnoremap <silent> <space>C :call ClearRegs()<CR>

set incsearch
