#!/bin/sh
alias	c="clear" \
	g="git" \
	ga="git add" \
	gcm="git commit -m" \
	gp="git pull" \
	gs="clear && echo "" && ls -aCF && git status" \
	l="clear && echo "" && ls" \
	lk="clear && echo "" && ls -aC" \
	ll="clear && echo "" && ls -l" \
	ni="npm install" \
	p="sudo pacman" \
	pi="sudo pip3 install" \
	pip="sudo pip3" \
	py="python3" \
	s="sudo" \
    t="tig" \
	v="vim" \
	ydv="youtube-dl -i --add-metadata -o '[%(upload_date)s] %(title)s.%(ext)s'" \
    301="cd ~/Academia/301" \
    326="cd ~/Academia/326" \
    330="cd ~/Academia/330" \
    333="cd ~/Academia/333" \
    353="cd ~/Academia/353" \
    jj="cd ~/Repos/Jargon/services && l" \
    r='SHELL=/usr/local/bin/r.shell ranger' \
    z="zathura"
	
