#!/bin/sh
alias	c="clear" \
    bash='bash --rcfile .config/bash/.bashrc' \
    calcurse='calcurse -D "$HOME/.config/calcurse" -C "$HOME/.config/calcurse"' \
	g="git" \
	ga="git add" \
	gcm="git commit -m" \
	gp="git pull" \
    hc="herbstclient" \
	l="clear && echo "" && ls" \
	lk="clear && echo "" && ls -aC" \
	ll="clear && echo "" && ls -l" \
	ni="npm install" \
	p="sudo pacman" \
	pi="sudo pip3 install" \
	pip="sudo pip3" \
	py="python3" \
    pym="python3 manage.py" \
	s="sudo" \
    t="tig" \
	v="nvim" \
	ydv="youtube-dl -i --add-metadata -o '[%(upload_date)s] %(title)s.%(ext)s'" \
    301="cd ~/Academia/301" \
    326="cd ~/Academia/326" \
    330="cd ~/Academia/330" \
    333="cd ~/Academia/333" \
    353="cd ~/Academia/353" \
    jj="cd ~/Repos/Jargon/services && l" \
    r='SHELL=/usr/local/bin/r.shell ranger' \
    igpu='sudo set-intel.sh' \
    dgpu='sudo set-nvidia.sh' \
    ssys='sudo systemctl' \
    sstart='sudo systemctl start' \
    sstop='sudo systemctl stop' \
    tmux='tmux -f .config/tmux/.tmux.conf' \
    z="zathura"
	
