#!/bin/sh

#〖愛〗shell aliases file

# This file is sourced by the shell config file. Put all 
# shell aliases in this file.

alias	\
LG="clear && echo "" && ls | grep" \
activate="source bin/activate" \
cf="source vpwd_cf" \
cp="cpg -g" \
emerge="doas emerge" \
eselect="doas eselect" \
g="git" \
gc="git clone" \
jj="cd ~/wk/sarrost-software/client/one-world/wk/one-world-web && l" \
l='ls' \
la="ls -a" \
f="source vpwd_lf" \
lk='ls -a | cut -c1-20 | column -c "${COLUMNS:-80}"' \
ll="ls -l" \
ls='ls --color=auto' \
lxa="lxmk; lxin; lxgr" \
lxgr="doas grub-mkconfig -o /boot/grub/grub.cfg" \
lxin="doas make install && doas make modules_install" \
lxmk="doas make -j$(nproc) && doas make -j$(nproc) modules" \
mv="mvg -g" \
n="source n" \
py="python3" \
pym="python3 manage.py" \
sc="sc-im" \
t="task" \
torr="transmission-remote-cli" \
up="doas up" \
v="nvim" \
vs="vs" \
vw="v $RICE_NOTES_DIR/index.mdox" \
ydv="youtube-dl -i --add-metadata -o '[%(upload_date)s] %(title)s.%(ext)s'" \
z="zathura" \
bbb="bitcoin-chart-cli -w 60 -d 7" \
btt="bitcoin-chart-cli -w 60 -h 12 -d 30" \
btc="bitcoin-chart-cli -w 60 -h 12 -d 90" \



