#!/bin/sh

#〖愛〗Shell aliases file.
#
# This file is sourced by the shell config file. Put all 
# shell aliases in this file.

alias	\
bash='bash --rcfile .config/bash/.bashrc' \
activate='source bin/activate' \
vifm='vifmrun' \
sc='sc-im' \
calcurse='calcurse -D "$HOME/.config/calcurse" -C "$HOME/.config/calcurse"' \
g="git" \
hc="herbstclient" \
ls="ls --color=auto" \
l="clear && echo "" && ls" \
la="clear && echo "" && ls -a" \
lk="clear && echo "" && ls -aC" \
ll="clear && echo "" && ls -l" \
ni="npm install" \
p="sudo pacman" \
pi="sudo pip3 install" \
pip="sudo pip3" \
py="python3" \
pym="python3 manage.py" \
s="sudo" \
t="tig" \
v="nvim" \
ydv="youtube-dl -i --add-metadata -o '[%(upload_date)s] %(title)s.%(ext)s'" \
301="cd ~/Academia/301" \
326="cd ~/Academia/326" \
330="cd ~/Academia/330" \
333="cd ~/Academia/333" \
353="cd ~/Academia/353" \
jj="cd ~/repo/sarrost-website && l" \
r='SHELL=/usr/local/bin/r.shell ranger' \
igpu='sudo set-intel.sh' \
dgpu='sudo set-nvidia.sh' \
sys='sudo systemctl' \
tmux='tmux -f .config/tmux/.tmux.conf' \
z="zathura" \
PQ="pacman -Q | grep" \
LG="clear && echo "" && ls | grep" \
