#!/bin/sh

#〖愛〗Shell aliases file.
#
# This file is sourced by the shell config file. Put all 
# shell aliases in this file.

alias	\
jj="cd ~/wk/sarrost/sarrost-com/src/ && l" \
activate="source bin/activate" \
vifm="source vpwd_vifm" \
cf="source vpwd_cf" \
sc="sc-im" \
calcurse="calcurse -D "$HOME/.config/calcurse" -C "$HOME/.config/calcurse"" \
g="git" \
hc="herbstclient" \
ls="ls --color=auto" \
l="ls" \
la="ls -a" \
lk="ls -aC" \
ll="ls -l" \
ni="npm install" \
p="sudo pacman" \
pi="sudo pip install" \
pip="sudo pip" \
py="python3" \
pym="python3 manage.py" \
t="tig" \
v="source vpwd_nvim" \
ydv="youtube-dl -i --add-metadata -o '[%(upload_date)s] %(title)s.%(ext)s'" \
r='SHELL=/usr/local/bin/r.shell ranger' \
igpu='sudo set-intel.sh' \
dgpu='sudo set-nvidia.sh' \
sys='sudo systemctl' \
tmux='tmux -f .config/tmux/.tmux.conf' \
z="zathura" \
torr="transmission-remote-cli" \
PQ="pacman -Q | grep" \
LG="clear && echo "" && ls | grep" \
vs="source vs" \
emerge="doas emerge" \
vw="v $RICE_NOTES_DIR/index.mdox" \
