#!/bin/zsh

# Prompt options
SPACESHIP_CHAR_SYMBOL=↪
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_CHAR_COLOR_SUCCESS="red"
SPACESHIP_CHAR_COLOR_FAILURE="yellow"
SPACESHIP_DIR_TRUNC=0
SPACESHIP_BATTERY_THRESHOLD=30
SPACESHIP_JOBS_SYMBOL=""
SPACESHIP_JOBS_AMOUNT_PREFIX=" "

# Set prompt
autoload -U promptinit; promptinit
prompt spaceship
