#!/bin/sh

# THIS FILE WAS AUTOGENERATED BY THE `genshortcuts` SCRIPT.

alias gan="cd $RICE_ANIME_DIR"
alias gam="cd $RICE_GAMES_DIR"
alias gar="cd $RICE_ARTICLES_DIR"
alias gco="cd $RICE_CODE_DIR"
alias gcf="cd $XDG_CONFIG_HOME"
alias gdc="cd $XDG_DOCUMENTS_DIR"
alias gdt="cd $RICE_DOTFILES_DIR"
alias gdl="cd $XDG_DOWNLOAD_DIR"
alias gli="cd $RICE_LIBRARY_DIR"
alias gls="cd $XDG_DATA_HOME"
alias gmd="cd $RICE_MEDIA_DIR"
alias gmn="cd $RICE_MOUNT_DIR"
alias gmu="cd $XDG_MUSIC_DIR"
alias gno="cd $RICE_NOTES_DIR"
alias gpc="cd $XDG_PICTURES_DIR"
alias grp="cd $RICE_REPOSITORY_DIR"
alias gs="cd $RICE_SCRIPTS_DIR"
alias gvi="cd $XDG_VIDEOS_DIR"
alias gtp="cd $XDG_TEMPLATES_DIR"
ypan(){ cp "$@" "$RICE_ANIME_DIR" }
ypam(){ cp "$@" "$RICE_GAMES_DIR" }
ypar(){ cp "$@" "$RICE_ARTICLES_DIR" }
ypco(){ cp "$@" "$RICE_CODE_DIR" }
ypcf(){ cp "$@" "$XDG_CONFIG_HOME" }
ypdc(){ cp "$@" "$XDG_DOCUMENTS_DIR" }
ypdt(){ cp "$@" "$RICE_DOTFILES_DIR" }
ypdl(){ cp "$@" "$XDG_DOWNLOAD_DIR" }
ypli(){ cp "$@" "$RICE_LIBRARY_DIR" }
ypls(){ cp "$@" "$XDG_DATA_HOME" }
ypmd(){ cp "$@" "$RICE_MEDIA_DIR" }
ypmn(){ cp "$@" "$RICE_MOUNT_DIR" }
ypmu(){ cp "$@" "$XDG_MUSIC_DIR" }
ypno(){ cp "$@" "$RICE_NOTES_DIR" }
yppc(){ cp "$@" "$XDG_PICTURES_DIR" }
yprp(){ cp "$@" "$RICE_REPOSITORY_DIR" }
yps(){ cp "$@" "$RICE_SCRIPTS_DIR" }
ypvi(){ cp "$@" "$XDG_VIDEOS_DIR" }
yptp(){ cp "$@" "$XDG_TEMPLATES_DIR" }
mvan(){ mv "$@" "$RICE_ANIME_DIR" }
mvam(){ mv "$@" "$RICE_GAMES_DIR" }
mvar(){ mv "$@" "$RICE_ARTICLES_DIR" }
mvco(){ mv "$@" "$RICE_CODE_DIR" }
mvcf(){ mv "$@" "$XDG_CONFIG_HOME" }
mvdc(){ mv "$@" "$XDG_DOCUMENTS_DIR" }
mvdt(){ mv "$@" "$RICE_DOTFILES_DIR" }
mvdl(){ mv "$@" "$XDG_DOWNLOAD_DIR" }
mvli(){ mv "$@" "$RICE_LIBRARY_DIR" }
mvls(){ mv "$@" "$XDG_DATA_HOME" }
mvmd(){ mv "$@" "$RICE_MEDIA_DIR" }
mvmn(){ mv "$@" "$RICE_MOUNT_DIR" }
mvmu(){ mv "$@" "$XDG_MUSIC_DIR" }
mvno(){ mv "$@" "$RICE_NOTES_DIR" }
mvpc(){ mv "$@" "$XDG_PICTURES_DIR" }
mvrp(){ mv "$@" "$RICE_REPOSITORY_DIR" }
mvs(){ mv "$@" "$RICE_SCRIPTS_DIR" }
mvvi(){ mv "$@" "$XDG_VIDEOS_DIR" }
mvtp(){ mv "$@" "$XDG_TEMPLATES_DIR" }
